receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  file:
    path: /var/lib/data.json
  logging:
    loglevel: debug
  otlphttp/hdx:
    endpoint: 'https://in-otel.hyperdx.io'
    headers:
      authorization: <YOUR_API_KEY>
    compression: gzip

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [file, logging, otlphttp/hdx]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [file, logging, otlphttp/hdx]
    logs:
      receivers: [otlp]
      processors: [batch]
      # exporters: [file, logging]
      exporters: [logging, otlphttp/hdx]
